# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
